*&---------------------------------------------------------------------*
*& Include          ZBRMM0040_TOP
*&---------------------------------------------------------------------*

DATA: OK_CODE TYPE SY-UCOMM,
      GS_VARIANT TYPE DISVARIANT.

TABLES: ZTBMM0060, ZTBMM0061, ZSBMM0060, ZSBMM0060_ALV1,
        ZSBMM0060_ALV2, ZSBMM0060_ALV3.

DATA: GO_CUST1 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ESPLIT TYPE REF TO CL_GUI_EASY_SPLITTER_CONTAINER,
      GO_CONT1 TYPE REF TO CL_GUI_CONTAINER,
      GO_CONT2 TYPE REF TO CL_GUI_CONTAINER,
      GO_GRID1 TYPE REF TO CL_GUI_ALV_GRID,
      GO_GRID2 TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYO1 TYPE LVC_S_LAYO,
      GS_LAYO2 TYPE LVC_S_LAYO,
      GS_FCAT1 TYPE LVC_S_FCAT,
      GT_FCAT1 TYPE LVC_T_FCAT,
      GS_FCAT2 TYPE LVC_S_FCAT,
      GT_FCAT2 TYPE LVC_T_FCAT.

* ALV1 WA & ITAB.
DATA: GS_DISPLAY1 TYPE ZSBMM0060_ALV1,
      GT_DISPLAY1 LIKE TABLE OF GS_DISPLAY1,
      GT_SORT1 TYPE LVC_T_SORT.


* ALV2 WA & ITAB.
DATA: GS_DISPLAY2 TYPE ZSBMM0060_ALV2,
      GT_DISPLAY2 LIKE TABLE OF GS_DISPLAY2,
      GT_SORT2 TYPE LVC_T_SORT.

* ALV1 SELECTED ROW ITAB & WA.
DATA: GT_ROW1 TYPE LVC_T_ROID,
      GS_ROW1 TYPE LVC_S_ROID.

* ALV2 SELECTED ROW ITAB & WA.
DATA: GT_ROW2 TYPE LVC_T_ROID,
      GS_ROW2 TYPE LVC_S_ROID.

* ALV3 WA & ITAB.
DATA: GS_DISPLAY3 TYPE ZSBMM0060_ALV3,
      GT_DISPLAY3 LIKE TABLE OF GS_DISPLAY3.

* ALV3 CONTAINER
DATA: GO_CUST2 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_GRID3 TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYO3 TYPE LVC_S_LAYO,
      GS_FCAT3 TYPE LVC_S_FCAT,
      GT_FCAT3 TYPE LVC_T_FCAT.
