*&---------------------------------------------------------------------*
*& Include          ZBRMM0040_C01
*&---------------------------------------------------------------------*

CLASS LCL_EVENT DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS:
      ON_TOOLBAR1 FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT,

      ON_USER_COMMAND1 FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM,

      ON_TOOLBAR2 FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT,

      ON_USER_COMMAND2 FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM.
ENDCLASS.

CLASS LCL_EVENT IMPLEMENTATION.
  METHOD ON_TOOLBAR1.
    PERFORM HANDLE_TOOLBAR1 USING E_OBJECT. " ALV1 toolbar 버튼 생성
  ENDMETHOD.

  METHOD ON_USER_COMMAND1.
    PERFORM HANDLE_USER_COMMAND1 USING E_UCOMM. " ALV1 toolbar 버튼 클릭 시 이벤트
  ENDMETHOD.

  METHOD ON_TOOLBAR2.
    PERFORM HANDLE_TOOLBAR2 USING E_OBJECT. " ALV2 toolbar 버튼 생성
  ENDMETHOD.

  METHOD ON_USER_COMMAND2.
    PERFORM HANDLE_USER_COMMAND2 USING E_UCOMM. " ALV2 toolbar 버튼 클릭 시 이벤트
  ENDMETHOD.
ENDCLASS.
